name: Builds

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "build.gradle.kts"
      - "settings.gradle.kts"
  pull_request:
    types: ["opened", "reopened"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
          gradle-version: 8.7
    - name: Build
      run: gradle jar
    - name: Copy Files
      run: |
        mkdir out
        cp build/libs/* out/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: dev-artifact
        path: out/
